version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: crazySupplierServer
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    restart: unless-stopped
